name: 'Yarn Package Publish'
description: 'Will automatically publish unpublished package versions to the given registry.'
author: 'luvies'
inputs:
  package-path:
    description: 'The path to the root directory containing the package.json.'
  dry-run:
    description: 'If set to true, all actions that would have been performed are skipped.'
    default: 'false'
  skipped-versions:
    description: 'A semver string of the versions to skip publishing of (see https://npm.im/semver for syntax).'
  git-tag:
    description: 'Whether to also tag the current commit with the version.'
    default: 'false'
  git-tag-format:
    description: 'The format the git tag should use ({version} is replaced by the package.json version).'
    default: 'v{version}'
runs:
  using: 'node12'
  main: 'build/action.js'
branding:
  icon: 'upload-cloud'
  color: 'blue'
